trigger:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
- main

pool: 
  name: Hello
  demands:
  - agent.name  -equals Agent1

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      
      echo "Hello world"


