
trigger:
- main

pool:
  name: Agent1
  demands:
  - agent.name  -equals Hello
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'